version: '2.2'

networks:
  integration-tests:
    driver: bridge

services:
  sut:
    image: golang:1.11.4
    links:
      - db:db
    networks:
      - integration-tests
    environment:
      - DATABASE_URL=bot:bot@tcp(db:3306)/bot?parseTime=true
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TZ=Asia/Bishkek
    working_dir: /go/src/github.com/maddevsio/mad-telegram-standup-bot
    volumes:
      - /go/src/github.com/maddevsio/mad-telegram-standup-bot:/go/src/github.com/maddevsio/mad-telegram-standup-bot
    command: bash -c "./goose -dir migrations mysql 'bot:bot@tcp(db:3306)/bot' up && go test -v -timeout 30s ./... "
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: bot
      MYSQL_PASSWORD: bot
      MYSQL_DATABASE: bot
    healthcheck:
      test: "mysql -ubot --password=bot -e 'show databases;' |grep bot"
      interval: 3s
      timeout: 5s
      retries: 10
    networks:
      - integration-tests

